services:
  lamese-ai:
    build:
      context: .
      dockerfile: Dockerfile
    image: lamese-ai:0.1.0
    container_name: lamese-ai
    ports:
      - "8000:8000"
    environment:
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    restart: unless-stopped