import pandas as pd
import numpy as np
from sklearn.pipeline import Pipeline
from app.ml.exceptions import PredictionError
from app.core.logger import logger


def predict(
    pipeline: Pipeline,
    new_patient: pd.DataFrame,
) -> np.ndarray:
    """
    Generate predictions using a trained ML pipeline.

    Args:
        pipeline: Trained machine learning pipeline.
        new_patient: New unseen data.

    Returns:
        Predictions generated by the model.
    """

    try:
        prediction = pipeline.predict(new_patient)

    except Exception as error:

        logger.exception(
            "Prediction failed."
        )

        raise PredictionError(
            "Failed to generate prediction."
        ) from error



    return prediction


def predict_probability(
    pipeline: Pipeline,
    new_patient: pd.DataFrame,
) -> np.ndarray:
    """
    Generate class probabilities using a trained ML pipeline.

    Args:
        pipeline: Trained machine learning pipeline.
        new_patient: New unseen patient data.

    Returns:
        Class probabilities generated by the model.
    """

    try:
        probability = pipeline.predict_proba(new_patient)

    except Exception as error:

        logger.exception(
            "Prediction probability calculation failed."
        )

        raise PredictionError(
            "Failed to generate prediction probabilities."
        ) from error

    return probability